#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping shutdown listener...\n"
sudo update-rc.d listen-for-shutdown.sh remove
sudo /etc/init.d/listen-for-shutdown.sh stop

echo "=> Removing shutdown listener...\n"
sudo rm -rf /usr/local/bin/listen-for-shutdown.py 
sudo rm -rf /etc/init.d/listen-for-shutdown.sh 

echo "Shutdown listener uninstalled.\n"

echo "=> Stopping restart listener...\n"
sudo update-rc.d listen-for-restart.sh remove
sudo /etc/init.d/listen-for-restart.sh stop

echo "=> Removing restart listener...\n"
sudo rm -rf /usr/local/bin/listen-for-restart.py 
sudo rm -rf /etc/init.d/listen-for-restart.sh 

echo "Restart listener uninstalled.\n"
echo "Developed by howchoo.com, expanded by Peter Brittain (KindarConrath)"
